services:

  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: airflow-webserver
    build:
      context: .
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scrapping:/opt/airflow/scrapping
      - ./requirements.txt:/requirements.txt

    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.10.5
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=60
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scrapping:/opt/airflow/scrapping
    command: ["airflow", "scheduler"]
    networks:
      - airflow_network

  airflow-worker:
    image: apache/airflow:2.10.5
    restart: always
    depends_on:
      - airflow-webserver
      - airflow-scheduler
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__WEBSERVER__WORKERS=1
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: ["celery", "worker"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scrapping:/opt/airflow/scrapping
    networks:
      - airflow_network


  postgres:
    image: postgres:17
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    networks:
      - airflow_network

  redis:
    image: redis:latest
    container_name: airflow-redis
    restart: always
    networks:
      - airflow_network

volumes:
  postgres_data:

networks:
  airflow_network:
    driver: bridge
